Removing dbus dependency and sandboxing app
JensTimmerman/ansible-role-vaultwarden pull request #22
Opened 2023-03-07 23:36 UTC by chadek

While I tried this role, handlers failed restarting vaultwarden service because of missing dbus package which seems to be a desktop related component. I suggest to discard it. I also added some sandboxing option base on my systemd knowledge and this service file: https://gist.github.com/tavinus/59c314f4ccd70879db7f11074eacb6cc

2023-03-11 15:00 UTC, JensTimmerman requested changes

2023-03-11 15:00 UTC, JensTimmerman commented on templates/systemd.service.j2
> +EnvironmentFile={{ vaultwarden_directory }}/.env
These 2 lines above are already included 13 lines up.

2023-03-11 15:00 UTC, JensTimmerman commented on templates/systemd.service.j2
> +AmbientCapabilities=CAP_NET_BIND_SERVICE
should only be set if {{ vaultwarden_port }}  is < 1025?

2023-03-13 20:27 UTC, chadek commented on templates/systemd.service.j2
> +AmbientCapabilities=CAP_NET_BIND_SERVICE
CAP_NET_BIND_SERVICE allow unprivileged process to bind the restricted port range (0-1024). I suggest to keep it like this even if you do not use a privileged port.

2023-03-13 20:37 UTC, chadek commented on templates/systemd.service.j2
> +EnvironmentFile={{ vaultwarden_directory }}/.env
Forgot to remove then. It's done

2023-03-13 22:59 UTC, JensTimmerman commented on templates/systemd.service.j2
> +AmbientCapabilities=CAP_NET_BIND_SERVICE
that would give this service/process more rights than it needs to? This strokes with the least privilege requirements one would typically try to enforce?

2023-03-14 08:24 UTC, chadek commented on templates/systemd.service.j2
> +AmbientCapabilities=CAP_NET_BIND_SERVICE
You are right: Vaultwarden documentation recommend to put it behind a reverse proxy, therefore we should not need to use a privileged port  and indeed remove this line

2023-03-14 22:45 UTC, JensTimmerman approved these changes

2023-03-16 10:29 UTC, chadek commented
Is this good to merge then?

2023-03-16 17:16 UTC, JensTimmerman commented
I'm having a look at the molecule tests, they don't seem to start your tests. I'd like to see them run on this, or test this on my qa before merging, I'll look at it when I find a bit of time later this week.

2023-03-17 20:53 UTC, chadek commented
I took a look on geerlingguy roles and it look like he does not make a use of verify.yml which is suppose to let you run some ansible tasks to check your environment after role is done running.  Anyway the content of what I provided is basically the example generated by molecule...
To test the role with molecule you should run molecule test or molecule converge if you want to inspect the container.

2023-05-03 09:38 UTC, chadek commented
Will this be merge someday? I used it on a production environment and so far so good. Just need to pay attention on having right permission on the vaultwarden_directory you choose :)

2023-05-03 17:06 UTC, merged